export type QRType = 
  | 'url' 
  | 'vcard' 
  | 'text' 
  | 'wifi' 
  | 'email' 
  | 'phone' 
  | 'sms' 
  | 'location' 
  | 'instagram' 
  | 'facebook' 
  | 'youtube' 
  | 'whatsapp';

export interface QRCodeData {
  id: string;
  name: string;
  type: QRType;
  content: string;
  template: QRTemplate;
  styling: QRStyling;
  createdAt: string;
  scans: number;
  status: 'active' | 'inactive';
}

export interface QRTemplate {
  id: string;
  name: string;
  backgroundColor: string;
  textColor: string;
  title: string;
  subtitle: string;
  // Extended styling options
  titleFontSize?: number;
  subtitleFontSize?: number;
  titleFontWeight?: 'normal' | 'medium' | 'semibold' | 'bold';
  subtitleFontWeight?: 'normal' | 'medium' | 'semibold' | 'bold';
  fontFamily?: string;
  textAlign?: 'left' | 'center' | 'right';
  qrPosition?: 'bottom' | 'center' | 'top';
  borderRadius?: number;
  showGradient?: boolean;
  gradientColor?: string;
  gradientDirection?: 'to-bottom' | 'to-right' | 'to-bottom-right' | 'to-top-right';
  padding?: number;
  // Advanced styling
  titleLetterSpacing?: number;
  subtitleLetterSpacing?: number;
  showBorder?: boolean;
  borderColor?: string;
  borderWidth?: number;
  shadowIntensity?: 'none' | 'light' | 'medium' | 'strong';
  decorativeStyle?: 'none' | 'circles' | 'dots' | 'lines' | 'geometric';
  accentColor?: string;
}

export interface QRStyling {
  fgColor: string;
  bgColor: string;
  size: number;
  level: 'L' | 'M' | 'Q' | 'H';
  includeMargin: boolean;
}

export interface VCardData {
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  company: string;
  title: string;
  website: string;
  address: string;
}

export interface DesignTemplate {
  id: string;
  name: string;
  category: 'business' | 'creative' | 'minimal' | 'vibrant';
  icon: string;
  fgColor: string;
  bgColor: string;
}

export const defaultStyling: QRStyling = {
  fgColor: '#000000',
  bgColor: '#ffffff',
  size: 200,
  level: 'M',
  includeMargin: true,
};

export const designTemplates: DesignTemplate[] = [
  { id: 'classic-black', name: 'Classic Black', category: 'minimal', icon: 'square', fgColor: '#000000', bgColor: '#ffffff' },
  { id: 'modern-gradient', name: 'Modern Gradient', category: 'vibrant', icon: 'sparkles', fgColor: '#8b5cf6', bgColor: '#fef3c7' },
  { id: 'business-pro', name: 'Business Professional', category: 'business', icon: 'building', fgColor: '#1e40af', bgColor: '#f8fafc' },
  { id: 'ocean-breeze', name: 'Ocean Breeze', category: 'creative', icon: 'waves', fgColor: '#0891b2', bgColor: '#ecfeff' },
  { id: 'sunset-vibes', name: 'Sunset Vibes', category: 'vibrant', icon: 'sun', fgColor: '#ea580c', bgColor: '#fff7ed' },
  { id: 'forest-green', name: 'Forest Green', category: 'creative', icon: 'tree', fgColor: '#166534', bgColor: '#f0fdf4' },
  { id: 'minimal-dots', name: 'Minimal Dots', category: 'minimal', icon: 'circle', fgColor: '#374151', bgColor: '#ffffff' },
  { id: 'neon-glow', name: 'Neon Glow', category: 'vibrant', icon: 'bolt', fgColor: '#c026d3', bgColor: '#fdf4ff' },
  { id: 'corporate-blue', name: 'Corporate Blue', category: 'business', icon: 'briefcase', fgColor: '#1d4ed8', bgColor: '#eff6ff' },
  { id: 'candy-pop', name: 'Candy Pop', category: 'creative', icon: 'candy', fgColor: '#db2777', bgColor: '#fdf2f8' },
];

export const defaultTemplates: QRTemplate[] = [
  // Professional & Business
  {
    id: 'professional-dark',
    name: 'Professional Dark',
    backgroundColor: '#1a1a2e',
    textColor: '#ffffff',
    title: 'Business Card',
    subtitle: 'Scan to connect',
    titleFontSize: 24,
    subtitleFontSize: 14,
    titleFontWeight: 'bold',
    fontFamily: 'Inter',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 16,
    showGradient: true,
    gradientColor: '#16213e',
    gradientDirection: 'to-bottom-right',
    padding: 24,
    shadowIntensity: 'medium',
    decorativeStyle: 'circles',
  },
  {
    id: 'corporate-blue',
    name: 'Corporate Blue',
    backgroundColor: '#1e40af',
    textColor: '#ffffff',
    title: 'Company Profile',
    subtitle: 'Learn more about us',
    titleFontSize: 22,
    subtitleFontSize: 13,
    titleFontWeight: 'bold',
    fontFamily: 'Inter',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 12,
    showGradient: true,
    gradientColor: '#3b82f6',
    gradientDirection: 'to-bottom',
    padding: 24,
    shadowIntensity: 'strong',
    decorativeStyle: 'geometric',
    accentColor: '#60a5fa',
  },
  // Luxury & Premium
  {
    id: 'luxury-gold',
    name: 'Luxury Gold',
    backgroundColor: '#1c1917',
    textColor: '#fbbf24',
    title: 'VIP Access',
    subtitle: 'Exclusive content',
    titleFontSize: 26,
    subtitleFontSize: 14,
    titleFontWeight: 'bold',
    fontFamily: 'Playfair Display',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 24,
    showGradient: true,
    gradientColor: '#292524',
    gradientDirection: 'to-bottom-right',
    padding: 28,
    showBorder: true,
    borderColor: '#fbbf24',
    borderWidth: 2,
    shadowIntensity: 'strong',
    decorativeStyle: 'lines',
    accentColor: '#f59e0b',
  },
  {
    id: 'rose-gold-premium',
    name: 'Rose Gold Premium',
    backgroundColor: '#18181b',
    textColor: '#fda4af',
    title: 'Premium Member',
    subtitle: 'Exclusive benefits await',
    titleFontSize: 24,
    subtitleFontSize: 13,
    titleFontWeight: 'bold',
    fontFamily: 'Playfair Display',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 20,
    showGradient: true,
    gradientColor: '#27272a',
    gradientDirection: 'to-bottom',
    padding: 26,
    showBorder: true,
    borderColor: '#fb7185',
    borderWidth: 1,
    shadowIntensity: 'medium',
    decorativeStyle: 'dots',
    accentColor: '#f43f5e',
  },
  // Vibrant & Creative
  {
    id: 'neon-cyber',
    name: 'Neon Cyber',
    backgroundColor: '#0f0f23',
    textColor: '#00ff88',
    title: 'Digital Hub',
    subtitle: 'Enter the matrix',
    titleFontSize: 26,
    subtitleFontSize: 14,
    titleFontWeight: 'bold',
    fontFamily: 'Space Grotesk',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 8,
    showGradient: true,
    gradientColor: '#1a1a3e',
    gradientDirection: 'to-bottom',
    padding: 24,
    showBorder: true,
    borderColor: '#00ff88',
    borderWidth: 2,
    shadowIntensity: 'strong',
    decorativeStyle: 'lines',
    accentColor: '#00ffff',
  },
  {
    id: 'sunset-gradient',
    name: 'Sunset Gradient',
    backgroundColor: '#ff6b6b',
    textColor: '#ffffff',
    title: 'Summer Vibes',
    subtitle: 'Catch the wave',
    titleFontSize: 24,
    subtitleFontSize: 14,
    titleFontWeight: 'bold',
    fontFamily: 'Poppins',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 24,
    showGradient: true,
    gradientColor: '#feca57',
    gradientDirection: 'to-bottom-right',
    padding: 26,
    shadowIntensity: 'medium',
    decorativeStyle: 'circles',
    accentColor: '#ff9ff3',
  },
  {
    id: 'aurora-purple',
    name: 'Aurora Purple',
    backgroundColor: '#667eea',
    textColor: '#ffffff',
    title: 'Creative Studio',
    subtitle: 'Imagination unleashed',
    titleFontSize: 24,
    subtitleFontSize: 13,
    titleFontWeight: 'semibold',
    fontFamily: 'Poppins',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 20,
    showGradient: true,
    gradientColor: '#764ba2',
    gradientDirection: 'to-bottom-right',
    padding: 24,
    shadowIntensity: 'strong',
    decorativeStyle: 'geometric',
    accentColor: '#a855f7',
  },
  {
    id: 'ocean-wave',
    name: 'Ocean Wave',
    backgroundColor: '#0077b6',
    textColor: '#ffffff',
    title: 'Dive Deep',
    subtitle: 'Explore the depths',
    titleFontSize: 24,
    subtitleFontSize: 13,
    titleFontWeight: 'bold',
    fontFamily: 'Inter',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 20,
    showGradient: true,
    gradientColor: '#00b4d8',
    gradientDirection: 'to-top-right',
    padding: 24,
    shadowIntensity: 'medium',
    decorativeStyle: 'circles',
    accentColor: '#90e0ef',
  },
  // Minimal & Clean
  {
    id: 'elegant-white',
    name: 'Elegant White',
    backgroundColor: '#ffffff',
    textColor: '#1f2937',
    title: 'Contact Info',
    subtitle: 'Professional networking',
    titleFontSize: 22,
    subtitleFontSize: 12,
    titleFontWeight: 'semibold',
    fontFamily: 'Inter',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 20,
    showGradient: false,
    padding: 28,
    showBorder: true,
    borderColor: '#e5e7eb',
    borderWidth: 1,
    shadowIntensity: 'light',
    decorativeStyle: 'none',
  },
  {
    id: 'minimalist',
    name: 'Minimalist',
    backgroundColor: '#f8fafc',
    textColor: '#0f172a',
    title: 'Simple QR',
    subtitle: 'Clean and modern',
    titleFontSize: 20,
    subtitleFontSize: 12,
    titleFontWeight: 'medium',
    fontFamily: 'Inter',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 12,
    showGradient: false,
    padding: 24,
    shadowIntensity: 'light',
    decorativeStyle: 'none',
  },
  // Nature & Organic
  {
    id: 'fresh-green',
    name: 'Fresh Green',
    backgroundColor: '#065f46',
    textColor: '#ffffff',
    title: 'Eco Friendly',
    subtitle: 'Sustainability matters',
    titleFontSize: 22,
    subtitleFontSize: 13,
    titleFontWeight: 'semibold',
    fontFamily: 'Inter',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 16,
    showGradient: true,
    gradientColor: '#10b981',
    gradientDirection: 'to-bottom-right',
    padding: 24,
    shadowIntensity: 'medium',
    decorativeStyle: 'circles',
    accentColor: '#34d399',
  },
  {
    id: 'forest-moss',
    name: 'Forest Moss',
    backgroundColor: '#14532d',
    textColor: '#bbf7d0',
    title: 'Go Green',
    subtitle: 'Nature first',
    titleFontSize: 24,
    subtitleFontSize: 13,
    titleFontWeight: 'bold',
    fontFamily: 'Poppins',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 16,
    showGradient: true,
    gradientColor: '#166534',
    gradientDirection: 'to-bottom',
    padding: 24,
    shadowIntensity: 'medium',
    decorativeStyle: 'dots',
    accentColor: '#4ade80',
  },
  // Bold & Energetic
  {
    id: 'ruby-red',
    name: 'Ruby Red',
    backgroundColor: '#991b1b',
    textColor: '#ffffff',
    title: 'Hot Deal',
    subtitle: "Don't miss out",
    titleFontSize: 24,
    subtitleFontSize: 14,
    titleFontWeight: 'bold',
    fontFamily: 'Inter',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 16,
    showGradient: true,
    gradientColor: '#dc2626',
    gradientDirection: 'to-bottom-right',
    padding: 24,
    shadowIntensity: 'strong',
    decorativeStyle: 'geometric',
    accentColor: '#f87171',
  },
  {
    id: 'warm-orange',
    name: 'Warm Orange',
    backgroundColor: '#c2410c',
    textColor: '#ffffff',
    title: 'Special Offer',
    subtitle: 'Limited time deal',
    titleFontSize: 22,
    subtitleFontSize: 13,
    titleFontWeight: 'bold',
    fontFamily: 'Inter',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 16,
    showGradient: true,
    gradientColor: '#ea580c',
    gradientDirection: 'to-bottom',
    padding: 24,
    shadowIntensity: 'medium',
    decorativeStyle: 'circles',
    accentColor: '#fb923c',
  },
  // Event & Social
  {
    id: 'soft-pink',
    name: 'Soft Pink',
    backgroundColor: '#be185d',
    textColor: '#ffffff',
    title: 'Event Invite',
    subtitle: 'Join us for something special',
    titleFontSize: 22,
    subtitleFontSize: 12,
    titleFontWeight: 'semibold',
    fontFamily: 'Poppins',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 24,
    showGradient: true,
    gradientColor: '#ec4899',
    gradientDirection: 'to-top-right',
    padding: 28,
    shadowIntensity: 'medium',
    decorativeStyle: 'dots',
    accentColor: '#f9a8d4',
  },
  {
    id: 'party-confetti',
    name: 'Party Confetti',
    backgroundColor: '#7c3aed',
    textColor: '#ffffff',
    title: "You're Invited!",
    subtitle: 'Save the date',
    titleFontSize: 26,
    subtitleFontSize: 14,
    titleFontWeight: 'bold',
    fontFamily: 'Poppins',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 24,
    showGradient: true,
    gradientColor: '#a855f7',
    gradientDirection: 'to-bottom-right',
    padding: 26,
    shadowIntensity: 'strong',
    decorativeStyle: 'dots',
    accentColor: '#fbbf24',
  },
  // Tech & Modern
  {
    id: 'slate-modern',
    name: 'Slate Modern',
    backgroundColor: '#334155',
    textColor: '#f1f5f9',
    title: 'Digital Card',
    subtitle: 'Tap to connect',
    titleFontSize: 22,
    subtitleFontSize: 13,
    titleFontWeight: 'semibold',
    fontFamily: 'Inter',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 20,
    showGradient: true,
    gradientColor: '#475569',
    gradientDirection: 'to-bottom',
    padding: 24,
    shadowIntensity: 'medium',
    decorativeStyle: 'lines',
    accentColor: '#94a3b8',
  },
  {
    id: 'midnight-tech',
    name: 'Midnight Tech',
    backgroundColor: '#020617',
    textColor: '#38bdf8',
    title: 'Tech Hub',
    subtitle: 'Innovation starts here',
    titleFontSize: 24,
    subtitleFontSize: 13,
    titleFontWeight: 'bold',
    fontFamily: 'Space Grotesk',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 12,
    showGradient: true,
    gradientColor: '#0f172a',
    gradientDirection: 'to-bottom-right',
    padding: 24,
    showBorder: true,
    borderColor: '#0ea5e9',
    borderWidth: 1,
    shadowIntensity: 'strong',
    decorativeStyle: 'geometric',
    accentColor: '#06b6d4',
  },
  // Food & Restaurant
  {
    id: 'cafe-brown',
    name: 'Café Brown',
    backgroundColor: '#78350f',
    textColor: '#fef3c7',
    title: 'Menu',
    subtitle: 'Scan for delicious options',
    titleFontSize: 26,
    subtitleFontSize: 14,
    titleFontWeight: 'bold',
    fontFamily: 'Playfair Display',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 16,
    showGradient: true,
    gradientColor: '#92400e',
    gradientDirection: 'to-bottom',
    padding: 24,
    shadowIntensity: 'medium',
    decorativeStyle: 'circles',
    accentColor: '#d97706',
  },
  {
    id: 'wine-burgundy',
    name: 'Wine Burgundy',
    backgroundColor: '#4c0519',
    textColor: '#fecdd3',
    title: 'Wine Menu',
    subtitle: 'Curated selections',
    titleFontSize: 24,
    subtitleFontSize: 13,
    titleFontWeight: 'semibold',
    fontFamily: 'Playfair Display',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 20,
    showGradient: true,
    gradientColor: '#881337',
    gradientDirection: 'to-bottom-right',
    padding: 26,
    shadowIntensity: 'strong',
    decorativeStyle: 'lines',
    accentColor: '#f43f5e',
  },
  // Social Media
  {
    id: 'instagram-gradient',
    name: 'Instagram Style',
    backgroundColor: '#833ab4',
    textColor: '#ffffff',
    title: 'Follow Me',
    subtitle: '@yourusername',
    titleFontSize: 24,
    subtitleFontSize: 14,
    titleFontWeight: 'bold',
    fontFamily: 'Poppins',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 24,
    showGradient: true,
    gradientColor: '#fd1d1d',
    gradientDirection: 'to-bottom-right',
    padding: 24,
    shadowIntensity: 'strong',
    decorativeStyle: 'circles',
    accentColor: '#fcb045',
  },
  {
    id: 'youtube-red',
    name: 'YouTube Red',
    backgroundColor: '#dc2626',
    textColor: '#ffffff',
    title: 'Subscribe',
    subtitle: 'Join the community',
    titleFontSize: 26,
    subtitleFontSize: 14,
    titleFontWeight: 'bold',
    fontFamily: 'Inter',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 16,
    showGradient: true,
    gradientColor: '#991b1b',
    gradientDirection: 'to-bottom',
    padding: 24,
    shadowIntensity: 'strong',
    decorativeStyle: 'geometric',
    accentColor: '#fca5a5',
  },
  // Ocean & Teal
  {
    id: 'ocean-teal',
    name: 'Ocean Teal',
    backgroundColor: '#0f766e',
    textColor: '#ffffff',
    title: 'Website Link',
    subtitle: 'Visit our site',
    titleFontSize: 20,
    subtitleFontSize: 13,
    titleFontWeight: 'semibold',
    fontFamily: 'Inter',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 16,
    showGradient: true,
    gradientColor: '#14b8a6',
    gradientDirection: 'to-top-right',
    padding: 24,
    shadowIntensity: 'medium',
    decorativeStyle: 'circles',
    accentColor: '#2dd4bf',
  },
  // Modern Purple
  {
    id: 'modern-purple',
    name: 'Modern Purple',
    backgroundColor: '#5b21b6',
    textColor: '#ffffff',
    title: 'My Portfolio',
    subtitle: 'View my work',
    titleFontSize: 24,
    subtitleFontSize: 14,
    titleFontWeight: 'bold',
    fontFamily: 'Poppins',
    textAlign: 'center',
    qrPosition: 'bottom',
    borderRadius: 20,
    showGradient: true,
    gradientColor: '#7c3aed',
    gradientDirection: 'to-bottom-right',
    padding: 24,
    shadowIntensity: 'strong',
    decorativeStyle: 'dots',
    accentColor: '#a78bfa',
  },
];